// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTeatnvHIZ1QM4fGeCorfxcbEo5B-6-K8',
    appId: '1:842416279774:web:b11a19155448575c98b24f',
    messagingSenderId: '842416279774',
    projectId: 'musicplayer-4589b',
    authDomain: 'musicplayer-4589b.firebaseapp.com',
    storageBucket: 'musicplayer-4589b.firebasestorage.app',
    measurementId: 'G-2K2L5MNDMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCQEioBWyLoEwKHNTBi678XDOHZ8JyIaQ',
    appId: '1:842416279774:android:3422bbead7a7ecdb98b24f',
    messagingSenderId: '842416279774',
    projectId: 'musicplayer-4589b',
    storageBucket: 'musicplayer-4589b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUSAy_3mc2w3QXd5UwrInDHh3mt6eLAuE',
    appId: '1:842416279774:ios:7c0b6b4768e93b4d98b24f',
    messagingSenderId: '842416279774',
    projectId: 'musicplayer-4589b',
    storageBucket: 'musicplayer-4589b.firebasestorage.app',
    iosBundleId: 'com.example.musicPlayer2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUSAy_3mc2w3QXd5UwrInDHh3mt6eLAuE',
    appId: '1:842416279774:ios:7c0b6b4768e93b4d98b24f',
    messagingSenderId: '842416279774',
    projectId: 'musicplayer-4589b',
    storageBucket: 'musicplayer-4589b.firebasestorage.app',
    iosBundleId: 'com.example.musicPlayer2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTeatnvHIZ1QM4fGeCorfxcbEo5B-6-K8',
    appId: '1:842416279774:web:8e8eef6cb3c7577198b24f',
    messagingSenderId: '842416279774',
    projectId: 'musicplayer-4589b',
    authDomain: 'musicplayer-4589b.firebaseapp.com',
    storageBucket: 'musicplayer-4589b.firebasestorage.app',
    measurementId: 'G-YXG30SK08P',
  );
}
